package com.justchat.util;

import java.io.*;
import java.nio.charset.Charset;
import java.util.Properties;

/**
 * JustChat
 *
 * @link https://github.com/brian978/JustChat
 * @copyright Copyright (c) 2014
 * @license Creative Commons Attribution-ShareAlike 3.0
 */
public class PropertiesHandler extends Properties
{
    protected String filename;

    public PropertiesHandler(String filename)
    {
        this.filename = filename;
    }

    public void load() throws IOException
    {
        load(new FileInputStream(new File(filename)));
    }

    public void store() throws IOException
    {
        FileOutputStream stream = new FileOutputStream(new File(filename));
        OutputStreamWriter writer = new OutputStreamWriter(stream, Charset.forName("UTF-8"));
        BufferedWriter bufferedWriter = new BufferedWriter(writer);

        store(bufferedWriter, "Generated by JustChat");
    }
}
